name = "beesweet"
compatibility_date = "2025-06-08"

[site]
bucket = "./dist"
entry-point = "."

[build]
command = "npm run build"  # or your build command

[env.production.vars]
NODE_ENV = "production"
