name = "beesweet"
compatibility_date = "2025-06-08"
workers_dev = true

type = "javascript"

[build]
command = "npm run build"
upload_format = "modules"

[site]
bucket = "./dist"
entry-point = "workers-site"

[env.production.vars]
NODE_ENV = "production"
