name = "beesweet"
compatibility_date = "2025-06-08"

type = "javascript"

[build]
command = "npm run build"
upload_format = "modules"

[site]
bucket = "./dist"
entry-point = "."

[env.production.vars]
NODE_ENV = "production"
